spring.datasource.url=jdbc:postgresql://dpg-d7kc8tt7vvec7398en6g-a:5432/demo_3884
spring.datasource.username=demo_3884_user
spring.datasource.password=NmEVc6kIRDYqf5mCRR9pjjqGOKZq5HLp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
